[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "sparkles"
author = "James Vogel"
author-email = "jim.m.vogel@gmail.com"
home-page = "https://github.com/voglster"
classifiers = ["License :: OSI Approved :: MIT License"]

